### ISSUE TITLE
Add hometown files (for Jacquie Witte)

### ISSUE THREAD

**Issue by eculler** [earthlab-education/ea-bootcamp-hometowns#159]
@jacquiewitte Please work on the following for next week:

- [ ] [Go to canvas and read the assignment 7 assignment page](https://canvas.colorado.edu/courses/75278/assignments/1100329
- [ ]  [Read the activity on EarthDataScience.org](https://www.earthdatascience.org/courses/intro-to-earth-data-science/git-github/github-collaboration/practice-pull-requests/)
- [ ] Fork this repository
- [ ] Complete the task of adding 4 Files to Your Fork of this repo
- [ ] Submit a pull request to add your changes

The files you will add are for **two towns** of your choice. You can select a place you've lived, a place you'd like to live or a place you live now! The files you add will look something like this ( [see the activity on EarthDataScience.org for details](https://www.earthdatascience.org/courses/intro-to-earth-data-science/git-github/github-collaboration/practice-pull-requests/))

- [ ] 2 .csv files: one for each city that you are submitting
- [ ] 2 .ipynb files (Jupyter Notebooks): one for each city that you are submitting

Once you have added your files, submit a pull request from your fork to the original EarthLab-Education repository to request that your changes be added.

**For details on what to include in each file and the pull request, [view the activity on EarthDataScience.org](https://www.earthdatascience.org/courses/intro-to-earth-data-science/git-github/github-collaboration/practice-pull-requests/)**

**Comment by jacquiewitte** [comment]
@eculler 
I submitted a PR for 1 .csv file, 1 .ipynb, plus an image file that is referenced by this jupyter notebook. 
This PR is #173 and addresses issue #159.  

Assignment 7 mentioned this was to be done **twice** so I assumed this is the first of two PR's. Apologies if I misinterpreted.

**Comment by jacquiewitte** [comment]
@eculler 
(FYI - if I remove the space between # and id number, it automatically finds the link to the issue.)

I have made another push to my fork repo that did not require a PR but was added to #173. Now I have 2 csv, 2 ipynb and 2 images pushed to my fork repo.
