### ISSUE TITLE
Issue for Eric Kennedy 

### ISSUE THREAD

**Issue by nkorinek** [earthlab-education/ea-bootcamp-hometowns#75]
@epkennedy120 Please work on the following for next week.

- [ ] go to canvas and read the assignment 7 assignment page closely
- [ ] then complete the task of adding 4 Files to Your Fork of this repo

For this assignment, you will be adding a new file for two different towns of your choice! If you attend class this week, you will complete adding at least the first town to your fork during class. The second you will do on your own outside of class. When you are done, you will have a total of 4 files in your pull request.

The files you will add are for two towns of your choice. You can select a place you've lived, a place you'd like to live or a place you live now! The files you add will look something like this:

- [ ] 2 .csv files: one for each city that you are submitting

- [ ] 2 .ipynb files (Jupyter Notebooks): one for each city that you are submitting

[View Activity on EarthDataScience.org](https://www.earthdatascience.org/courses/intro-to-earth-data-science/git-github/github-collaboration/practice-pull-requests/)

in each ipynb file, you will add:

- [ ] a subtitle (header) and the information for the latitude and longitude of the main area of the town/city
- [ ] a subtitle (header) and the information for the most recent population figure you can find, plus a hyperlink to the source for this information
- [ ] a subtitle (header) for a local landmark,
- [ ] an image and short text description of this landmark. Ideally you will use a linked image online to the landmark above and avoid adding the image to the repo!

**Comment by lisestdenis** [comment]
Assignment completed by @epkennedy120
